"""Declarative list of composed marketing images.

Add a new composite by appending a CollageSpec below (or to a new
per-screen list) — no changes to compose_lib.py needed. Mirrors how
integration_test/marketing/ adds a new runScenario call per screenshot.
"""

import dataclasses

from compose_lib import CollageSpec, Position, SplitImage, WindowSpec


def _in_folder(folder: str, collages: list[CollageSpec]) -> list[CollageSpec]:
    """Prefixes each collage's output with `folder/`, so screens land in their own subdirectory."""
    return [dataclasses.replace(c, output=f"{folder}/{c.output}") for c in collages]

POS_TOP_LEFT = Position(0, 0)
POS_TOP_CENTER = Position(700, 0)
POS_TOP_RIGHT = Position(1400, 0)
POS_MIDDLE_LEFT = Position(0, 1000)
POS_MIDDLE_CENTER = Position(700, 1000)
POS_MIDDLE_RIGHT = Position(1400, 1000)
POS_BOTTOM_LEFT = Position(0, 1380)
POS_BOTTOM_CENTER = Position(700, 1380)
POS_BOTTOM_RIGHT = Position(1400, 1380)

POS_HERO_BACK_LEFT = Position(0, 200)
POS_HERO_BACK_RIGHT = Position(1400, 200)
POS_HERO_MIDDLE_CENTER = Position(700, 500)
POS_HERO_FRONT_CENTER = Position(250, 1600)

HERO_SCREEN_COLLAGES: list[CollageSpec] = [
    CollageSpec(
        output="Hero.webp",
        windows=[
            WindowSpec(
                input="select_script_screen/foss.png",
                title="TiefPrompt",
                position=POS_HERO_BACK_LEFT,
            ),
            WindowSpec(
                input="home_screen/dark_pink_primary.png",
                title="TiefPrompt",
                position=POS_HERO_BACK_RIGHT,
            ),
            WindowSpec(
                input="home_screen/prefilled.png",
                title="TiefPrompt",
                position=POS_HERO_MIDDLE_CENTER,
            ),
            WindowSpec(
                input="prompter_screen/configured_script.png",
                title="TiefPrompt",
                position=POS_HERO_FRONT_CENTER,
            ),
        ],
    ),
]

HOME_SCREEN_COLLAGES: list[CollageSpec] = [
    CollageSpec(
        output="OpenSettings.webp",
        windows=[
            WindowSpec(
                input="home_screen_highlights/settings.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
            WindowSpec(
                input="main_settings_screen/light_theme.png",
                title="TiefPrompt",
                position=POS_TOP_RIGHT,
            ),
        ],
    ),
    CollageSpec(
        output="TitleBox.webp",
        windows=[
            WindowSpec(
                input="home_screen_highlights/title_box.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
        ],
    ),
    CollageSpec(
        output="ScriptContentBox.webp",
        windows=[
            WindowSpec(
                input="home_screen_highlights/content_box.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
        ],
    ),
    CollageSpec(
        output="PrimaryButtons.webp",
        windows=[
            WindowSpec(
                input="home_screen_highlights/primary_buttons.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
        ],
    ),
    CollageSpec(
        output="Variant.webp",
        windows=[
            WindowSpec(
                input="home_screen_highlights/variant_highlight.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
            WindowSpec(
                input="home_screen_highlights/variant_popup.png",
                title="TiefPrompt",
                position=POS_TOP_RIGHT,
            ),
        ],
    ),
    CollageSpec(
        output="VariantFoss.webp",
        windows=[
            WindowSpec(
                input="home_screen/foss.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
            WindowSpec(
                input="home_screen/foss_popup.png",
                title="TiefPrompt",
                position=POS_TOP_RIGHT,
            ),
        ],
    ),
    CollageSpec(
        output="VariantFree.webp",
        windows=[
            WindowSpec(
                input="home_screen/freemium_free.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
            WindowSpec(
                input="home_screen/freemium_free_popup.png",
                title="TiefPrompt",
                position=POS_TOP_RIGHT,
            ),
        ],
    ),
    CollageSpec(
        output="VariantPro.webp",
        windows=[
            WindowSpec(
                input="home_screen/freemium_pro.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
            WindowSpec(
                input="home_screen/freemium_pro_popup.png",
                title="TiefPrompt",
                position=POS_TOP_RIGHT,
            ),
        ],
    ),
    CollageSpec(
        output="StartButton.webp",
        windows=[
            WindowSpec(
                input="home_screen_highlights/start_button.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
            WindowSpec(
                input="prompter_screen_narrow/defaults.png",
                title="TiefPrompt",
                position=Position(350, 800),
            ),
        ],
    ),
]

MAIN_SETTINGS_SCREEN_COLLAGES: list[CollageSpec] = [
    CollageSpec(
        output="ChangeLanguage.webp",
        windows=[
            WindowSpec(
                input="main_settings_screen/change_language.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
            WindowSpec(
                input="main_settings_screen/german.png",
                title="TiefPrompt",
                position=POS_TOP_RIGHT,
            )
        ],
    ),
    CollageSpec(
        output="ChangeTheme.webp",
        windows=[
            WindowSpec(
                input="main_settings_screen/change_theme.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
            WindowSpec(
                input="main_settings_screen/dark_theme_open.png",
                title="TiefPrompt",
                position=POS_TOP_RIGHT,
            )
        ],
    ),
    CollageSpec(
        output="KeybindingsSettings.webp",
        windows=[
            WindowSpec(
                input="main_settings_screen/keybindings_highlight.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
            WindowSpec(
                input="keybindings_settings_screen/light_theme.png",
                title="TiefPrompt",
                position=POS_TOP_RIGHT,
            ),
        ],
    ),
    CollageSpec(
        output="SaveAndRestoreSettings.webp",
        windows=[
            WindowSpec(
                input="main_settings_screen/save_and_restore_highlight.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
            WindowSpec(
                input="settings_restore_screen/light_theme.png",
                title="TiefPrompt",
                position=POS_TOP_RIGHT,
            ),
        ],
    ),
    CollageSpec(
        output="PrimaryColor.webp",
        windows=[
            WindowSpec(
                input="main_settings_screen/primary_color_highlight.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
            WindowSpec(
                input="main_settings_screen/primary_color_picker.png",
                title="TiefPrompt",
                position=POS_TOP_CENTER,
            ),
            WindowSpec(
                input="home_screen/teal_primary.png",
                title="TiefPrompt",
                position=POS_TOP_RIGHT,
            ),
        ],
    ),
]

SETTINGS_SUBSCREENS_COLLAGES: list[CollageSpec] = [
    CollageSpec(
        output="DisplaySettingsScreen.webp",
        windows=[
            WindowSpec(
                input="main_settings_screen/display_settings_highlight.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
            WindowSpec(
                input="display_settings_screen/light_theme.png",
                title="TiefPrompt",
                position=POS_TOP_RIGHT,
            ),
        ],
    ),
    CollageSpec(
        output="DisplayAndTextSettings.webp",
        windows=[
            WindowSpec(
                input="display_settings_screen/light_theme.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
            WindowSpec(
                input="text_settings_screen/light_theme.png",
                title="TiefPrompt",
                position=POS_TOP_RIGHT,
            ),
        ],
    ),
]

TEXT_SETTINGS_SCREEN_COLLAGES: list[CollageSpec] = [
    CollageSpec(
        output="TextSettingsScreen.webp",
        windows=[
            WindowSpec(
                input="main_settings_screen/text_settings_highlight.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
            WindowSpec(
                input="text_settings_screen/light_theme.png",
                title="TiefPrompt",
                position=POS_TOP_RIGHT,
            ),
        ],
    ),
    CollageSpec(
        output="DefaultFontSize.webp",
        windows=[
            WindowSpec(
                input="text_settings_screen/default_font_size_highlight.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
            WindowSpec(
                input="text_settings_screen/default_font_size_dialog.png",
                title="TiefPrompt",
                position=POS_TOP_RIGHT,
            ),
        ],
    ),
    CollageSpec(
        output="TextAlignment.webp",
        windows=[
            WindowSpec(
                input="text_settings_screen/text_alignment_highlight.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
            WindowSpec(
                input="text_settings_screen/text_alignment_open.png",
                title="TiefPrompt",
                position=POS_TOP_RIGHT,
            ),
        ],
    ),
    CollageSpec(
        output="FontFamily.webp",
        windows=[
            WindowSpec(
                input="text_settings_screen/font_family_highlight.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
            WindowSpec(
                input="text_settings_screen/font_family_open.png",
                title="TiefPrompt",
                position=POS_TOP_RIGHT,
            ),
        ],
    ),
    CollageSpec(
        output="EnableMarkdown.webp",
        windows=[
            WindowSpec(
                input="text_settings_screen/enable_markdown_highlight.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
        ],
    ),
    CollageSpec(
        output="ShowCurrentChapter.webp",
        windows=[
            WindowSpec(
                input="text_settings_screen/show_current_chapter_highlight.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
        ],
    ),
]

CUSTOM_FONT_SETTINGS_SCREEN_COLLAGES: list[CollageSpec] = [
    CollageSpec(
        output="CustomFonts.webp",
        windows=[
            WindowSpec(
                input="text_settings_screen/custom_fonts_highlight.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
            WindowSpec(
                input="font_settings_screen/foss.png",
                title="TiefPrompt",
                position=POS_TOP_RIGHT,
            ),
        ],
    ),
    CollageSpec(
        output="RenameFontFamily.webp",
        windows=[
            WindowSpec(
                input="font_settings_screen/rename_highlight.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
            WindowSpec(
                input="font_settings_screen/rename_dialog.png",
                title="TiefPrompt",
                position=POS_TOP_RIGHT,
            ),
        ],
    ),
    CollageSpec(
        output="MoveFontVariant.webp",
        windows=[
            WindowSpec(
                input="font_settings_screen/family_highlight.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
            WindowSpec(
                input="font_settings_screen/move_highlight.png",
                title="TiefPrompt",
                position=POS_TOP_CENTER,
            ),
            WindowSpec(
                input="font_settings_screen/move_dialog.png",
                title="TiefPrompt",
                position=POS_TOP_RIGHT,
            ),
        ],
    ),
    CollageSpec(
        output="RemoveFontVariantFamilyRemains.webp",
        windows=[
            WindowSpec(
                input="font_settings_screen/remove_variant_highlight.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
            WindowSpec(
                input="font_settings_screen/remove_variant_complete.png",
                title="TiefPrompt",
                position=POS_TOP_RIGHT,
            ),
        ],
    ),
    CollageSpec(
        output="RemoveFontVariantFamilyRemoved.webp",
        windows=[
            WindowSpec(
                input="font_settings_screen/remove_last_variant_highlight.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
            WindowSpec(
                input="font_settings_screen/remove_last_variant_complete.png",
                title="TiefPrompt",
                position=POS_TOP_RIGHT,
            ),
        ],
    ),
    CollageSpec(
        output="EditFontVariant.webp",
        windows=[
            WindowSpec(
                input="font_settings_screen/edit_variant_highlight.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
            WindowSpec(
                input="font_settings_screen/edit_variant_dialog.png",
                title="TiefPrompt",
                position=POS_TOP_RIGHT,
            ),
        ],
    ),
]

SAVED_SETTINGS_SCREEN_COLLAGES: list[CollageSpec] = [
    CollageSpec(
        output="SaveSettings.webp",
        windows=[
            WindowSpec(
                input="settings_restore_screen/save_highlight.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
            WindowSpec(
                input="settings_restore_screen/save_dialog.png",
                title="TiefPrompt",
                position=POS_TOP_CENTER,
            ),
            WindowSpec(
                input="settings_restore_screen/save_complete.png",
                title="TiefPrompt",
                position=POS_TOP_RIGHT,
            ),
        ],
    ),
    CollageSpec(
        output="ExportSettings.webp",
        windows=[
            WindowSpec(
                input="settings_restore_screen/export_highlight.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
            WindowSpec(
                input="settings_restore_screen/export_dialog_highlight.png",
                title="TiefPrompt",
                position=POS_TOP_RIGHT,
            ),
        ],
    ),
    CollageSpec(
        output="ImportSettings.webp",
        windows=[
            WindowSpec(
                input="settings_restore_screen/import_highlight.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
            WindowSpec(
                input="settings_restore_screen/import_dialog_highlight.png",
                title="TiefPrompt",
                position=POS_TOP_CENTER,
            ),
            WindowSpec(
                input="settings_restore_screen/import_complete.png",
                title="TiefPrompt",
                position=POS_TOP_RIGHT,
            ),
        ],
    ),
    CollageSpec(
        output="RestoreSuccess.webp",
        windows=[
            WindowSpec(
                input="settings_restore_screen/restore_highlight.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
            WindowSpec(
                input="settings_restore_screen/restore_success.png",
                title="TiefPrompt",
                position=POS_TOP_RIGHT,
            ),
        ],
    ),
    CollageSpec(
        output="DeleteSettings.webp",
        windows=[
            WindowSpec(
                input="settings_restore_screen/delete_highlight.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
            WindowSpec(
                input="settings_restore_screen/delete_dialog_highlight.png",
                title="TiefPrompt",
                position=POS_TOP_CENTER,
            ),
            WindowSpec(
                input="settings_restore_screen/delete_complete.png",
                title="TiefPrompt",
                position=POS_TOP_RIGHT,
            ),
        ],
    ),
    CollageSpec(
        output="SavedSettingsScreen.webp",
        windows=[
            WindowSpec(
                input="main_settings_screen/save_and_restore_highlight.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
            WindowSpec(
                input="settings_restore_screen/saved_settings.png",
                title="TiefPrompt",
                position=POS_TOP_RIGHT,
            ),
        ],
    ),
]

KEYBINDINGS_SETTINGS_SCREEN_COLLAGES: list[CollageSpec] = [
    CollageSpec(
        output="PlayPause.webp",
        windows=[
            WindowSpec(
                input="keybindings_settings_screen/play_pause_highlight.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
            WindowSpec(
                input="keybindings_settings_screen/play_pause_dialog.png",
                title="TiefPrompt",
                position=POS_TOP_RIGHT,
            ),
        ],
    ),
    CollageSpec(
        output="AddBinding.webp",
        windows=[
            WindowSpec(
                input="keybindings_settings_screen/add_binding_highlight.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
            WindowSpec(
                input="keybindings_settings_screen/add_binding_dialog.png",
                title="TiefPrompt",
                position=POS_TOP_RIGHT,
            ),
        ],
    ),
    CollageSpec(
        output="RemoveBinding.webp",
        windows=[
            WindowSpec(
                input="keybindings_settings_screen/custom_binding_dialog.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
            WindowSpec(
                input="keybindings_settings_screen/play_pause_dialog.png",
                title="TiefPrompt",
                position=POS_TOP_RIGHT,
            ),
        ],
    ),
]

DISPLAY_SETTINGS_SCREEN_COLLAGES: list[CollageSpec] = [
    CollageSpec(
        output="ScrollSpeed.webp",
        windows=[
            WindowSpec(
                input="display_settings_screen/scroll_speed_highlight.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
            WindowSpec(
                input="display_settings_screen/scroll_speed_dialog.png",
                title="TiefPrompt",
                position=POS_TOP_RIGHT,
            ),
        ],
    ),
    CollageSpec(
        output="Flip.webp",
        windows=[
            WindowSpec(
                input="display_settings_screen/flip_highlight.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
        ],
    ),
    CollageSpec(
        output="ControlButtonsEnable.webp",
        windows=[
            WindowSpec(
                input="display_settings_screen/control_buttons_enable_highlight.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
        ],
    ),
    CollageSpec(
        output="ControlButtonsPosition.webp",
        windows=[
            WindowSpec(
                input="display_settings_screen/control_buttons_position_highlight.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
            WindowSpec(
                input="display_settings_screen/control_buttons_position_open.png",
                title="TiefPrompt",
                position=POS_TOP_RIGHT,
            ),
        ],
    ),
    CollageSpec(
        output="ReadingIndicators.webp",
        windows=[
            WindowSpec(
                input="display_settings_screen/reading_indicators_highlight.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
        ],
    ),
    CollageSpec(
        output="ReadingIndicatorsHeight.webp",
        windows=[
            WindowSpec(
                input="display_settings_screen/reading_indicators_height_highlight.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
            WindowSpec(
                input="display_settings_screen/reading_indicators_height_dialog.png",
                title="TiefPrompt",
                position=POS_TOP_RIGHT,
            ),
        ],
    ),
    CollageSpec(
        output="VerticalMarginsEnable.webp",
        windows=[
            WindowSpec(
                input="display_settings_screen/vertical_margins_enable_highlight.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
        ],
    ),
    CollageSpec(
        output="VerticalMarginsHeight.webp",
        windows=[
            WindowSpec(
                input="display_settings_screen/vertical_margins_height_highlight.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
            WindowSpec(
                input="display_settings_screen/vertical_margins_height_dialog.png",
                title="TiefPrompt",
                position=POS_TOP_RIGHT,
            ),
        ],
    ),
    CollageSpec(
        output="FadeEnable.webp",
        windows=[
            WindowSpec(
                input="display_settings_screen/fade_enable_highlight.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
        ],
    ),
    CollageSpec(
        output="FadeLength.webp",
        windows=[
            WindowSpec(
                input="display_settings_screen/fade_length_highlight.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
            WindowSpec(
                input="display_settings_screen/fade_length_dialog.png",
                title="TiefPrompt",
                position=POS_TOP_RIGHT,
            ),
        ],
    ),
    CollageSpec(
        output="SideMargin.webp",
        windows=[
            WindowSpec(
                input="display_settings_screen/side_margin_highlight.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
            WindowSpec(
                input="display_settings_screen/side_margin_dialog.png",
                title="TiefPrompt",
                position=POS_TOP_RIGHT,
            ),
        ],
    ),
    CollageSpec(
        output="CountdownTimer.webp",
        windows=[
            WindowSpec(
                input="display_settings_screen/countdown_timer_highlight.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
            WindowSpec(
                input="display_settings_screen/countdown_timer_dialog.png",
                title="TiefPrompt",
                position=POS_TOP_RIGHT,
            ),
        ],
    ),
    CollageSpec(
        output="PrompterBackgroundColor.webp",
        windows=[
            WindowSpec(
                input="display_settings_screen/prompter_background_color_highlight.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
            WindowSpec(
                input="display_settings_screen/prompter_background_color_dialog.png",
                title="TiefPrompt",
                position=POS_TOP_RIGHT,
            ),
            WindowSpec(
                input="prompter_screen/custom_background_color.png",
                title="TiefPrompt",
                position=POS_BOTTOM_LEFT,
            ),
        ],
    ),
    CollageSpec(
        output="PrompterTextColor.webp",
        windows=[
            WindowSpec(
                input="display_settings_screen/prompter_text_color_highlight.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
            WindowSpec(
                input="display_settings_screen/prompter_text_color_dialog.png",
                title="TiefPrompt",
                position=POS_TOP_RIGHT,
            ),
            WindowSpec(
                input="prompter_screen/custom_text_color.png",
                title="TiefPrompt",
                position=POS_BOTTOM_LEFT,
            ),
        ],
    ),
    CollageSpec(
        output="LockedFeature.webp",
        windows=[
            WindowSpec(
                input="display_settings_screen/locked_feature_highlight.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
            WindowSpec(
                input="buy_pro_screen/reading_indicator_boxes.png",
                title="TiefPrompt",
                position=POS_TOP_RIGHT,
            ),
        ],
    )
]

SELECT_SCRIPT_SCREEN_COLLAGES: list[CollageSpec] = [
    CollageSpec(
        output="SavedScriptsScreen.webp",
        windows=[
            WindowSpec(
                input="home_screen_highlights/select_script_button.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
            WindowSpec(
                input="select_script_screen/foss.png",
                title="TiefPrompt",
                position=POS_TOP_RIGHT,
            ),
        ],
    ),
    CollageSpec(
        output="SaveScript.webp",
        windows=[
            WindowSpec(
                input="home_screen_highlights/save_button.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
            WindowSpec(
                input="home_screen_highlights/save_dialog.png",
                title="TiefPrompt",
                position=POS_TOP_RIGHT,
            ),
        ],
    ),
    CollageSpec(
        output="LoadScript.webp",
        windows=[
            WindowSpec(
                input="select_script_screen/load_highlight.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
            WindowSpec(
                input="home_screen/loaded_script.png",
                title="TiefPrompt",
                position=POS_TOP_RIGHT,
            ),
        ],
    ),
    CollageSpec(
        output="DeleteScript.webp",
        windows=[
            WindowSpec(
                input="select_script_screen/delete_highlight.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
            WindowSpec(
                input="select_script_screen/delete_complete.png",
                title="TiefPrompt",
                position=POS_TOP_RIGHT,
            ),
        ],
    ),
    CollageSpec(
        output="ImportScript.webp",
        windows=[
            WindowSpec(
                input="select_script_screen/import_highlight.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
        ],
    ),
]

PROMPTER_SCREEN_COLLAGES: list[CollageSpec] = [
    CollageSpec(
        output="PrompterScreen.webp",
        windows=[
            WindowSpec(
                input="prompter_screen/configured_script.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
        ],
    ),
    CollageSpec(
        output="PrompterScreenOverlays.webp",
        windows=[
            WindowSpec(
                input="prompter_screen/overlays.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
        ],
    ),
    CollageSpec(
        output="MarkdownAndChapter.webp",
        windows=[
            WindowSpec(
                input="prompter_screen/markdown_and_chapter.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
        ],
    ),
]

HOME_CAROUSEL_COLLAGES: list[CollageSpec] = [
    CollageSpec(
        output="Home.webp",
        windows=[
            WindowSpec(
                input="home_screen_wide/foss.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
        ],
    ),
    CollageSpec(
        output="DistractionFreeReading.webp",
        windows=[
            WindowSpec(
                input="prompter_screen/configured_script_no_chrome.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
        ],
    ),
    CollageSpec(
        output="Personalize.webp",
        windows=[
            WindowSpec(
                input="prompter_screen/configured_script_format_overlay.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
        ],
    ),
]

FEATURE_SHOWCASE_COLLAGES: list[CollageSpec] = [
    CollageSpec(
        output="Fonts.webp",
        windows=[
            WindowSpec(
                input=SplitImage(
                    inputs=[
                        "prompter_screen/robotoslab_font.png",
                        "prompter_screen/roboto_font.png",
                        "prompter_screen/open_dyslexic_font.png",
                    ],
                    angle_deg=20,
                ),
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
        ],
    ),
    CollageSpec(
        output="MirrorModes.webp",
        windows=[
            WindowSpec(
                input="prompter_screen/mirrored_no_chrome.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
        ],
    ),
    CollageSpec(
        output="ReadingIndicators.webp",
        windows=[
            WindowSpec(
                input="prompter_screen/reading_indicators_no_chrome.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
        ],
    ),
    CollageSpec(
        output="Margins.webp",
        windows=[
            WindowSpec(
                input="prompter_screen/margins_no_chrome.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
        ],
    ),
    CollageSpec(
        output="Theming.webp",
        windows=[
            WindowSpec(
                input="prompter_screen/custom_colors_no_chrome.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
        ],
    ),
    CollageSpec(
        output="SavedScripts.webp",
        windows=[
            WindowSpec(
                input=SplitImage(
                    inputs=[
                        "select_script_screen_wide/foss.png",
                        "home_screen_wide/prefilled.png"
                    ],
                    angle_deg=20,
                ),
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
        ],
    ),
    CollageSpec(
        output="Markdown.webp",
        windows=[
            WindowSpec(
                input="prompter_screen/markdown_no_chrome.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
        ],
    ),
    CollageSpec(
        output="CountdownTimer.webp",
        windows=[
            WindowSpec(
                input="prompter_screen/countdown_timer_no_chrome.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
        ],
    ),
    CollageSpec(
        output="SettingsStorage.webp",
        windows=[
            WindowSpec(
                input="settings_restore_screen_wide/saved_settings.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
        ]
    ),
    CollageSpec(
        output="Keybindings.webp",
        windows=[
            WindowSpec(
                input="keybindings_settings_screen_wide/foss.png",
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
        ],
    ),
    CollageSpec(
        output="Typography.webp",
        windows=[
            WindowSpec(
                input=SplitImage(
                    inputs=[
                        "prompter_screen/crazy_typography_roboto.png",
                        "prompter_screen/crazy_typography_open_dyslexic.png",
                        "prompter_screen/crazy_typography_robotomono.png",
                    ],
                    angle_deg=20,
                ),
                title="TiefPrompt",
                position=POS_TOP_LEFT,
            ),
        ],
    ),
    
]

ALL_COLLAGES: list[CollageSpec] = (
    _in_folder("docs/hero", HERO_SCREEN_COLLAGES)
    + _in_folder("web", HOME_CAROUSEL_COLLAGES)
    + _in_folder("web/features", FEATURE_SHOWCASE_COLLAGES)
    + _in_folder("docs/home_screen", HOME_SCREEN_COLLAGES)
    + _in_folder("docs/main_settings_screen", MAIN_SETTINGS_SCREEN_COLLAGES)
    + _in_folder("docs/settings_subscreens", SETTINGS_SUBSCREENS_COLLAGES)
    + _in_folder("docs/text_settings_screen", TEXT_SETTINGS_SCREEN_COLLAGES)
    + _in_folder("docs/display_settings_screen", DISPLAY_SETTINGS_SCREEN_COLLAGES)
    + _in_folder("docs/keybindings_settings_screen", KEYBINDINGS_SETTINGS_SCREEN_COLLAGES)
    + _in_folder("docs/saved_settings_screen", SAVED_SETTINGS_SCREEN_COLLAGES)
    + _in_folder("docs/select_script_screen", SELECT_SCRIPT_SCREEN_COLLAGES)
    + _in_folder("docs/prompter_screen", PROMPTER_SCREEN_COLLAGES)
    + _in_folder("docs/font_settings_screen", CUSTOM_FONT_SETTINGS_SCREEN_COLLAGES)
)
