// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // ignore_for_file: type=lint,unused_import

// GENERATED BY drift_dev, DO NOT MODIFY.
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    scriptModel,
    settingsModel,
  ];
  late final Shape0 scriptModel = Shape0(
    source: i0.VersionedTable(
      entityName: 'script_model',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_1, _column_2, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 settingsModel = Shape1(
    source: i0.VersionedTable(
      entityName: 'settings_model',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_4,
        _column_3,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get scriptText =>
      columnsByName['script_text']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<int> _column_0(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'PRIMARY KEY AUTOINCREMENT',
      ),
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'script_text',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<DateTime> _column_3(String aliasedName) =>
    i1.GeneratedColumn<DateTime>(
      'created_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.dateTime,
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<double> get scrollSpeed =>
      columnsByName['scroll_speed']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<bool> get mirroredX =>
      columnsByName['mirrored_x']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<bool> get mirroredY =>
      columnsByName['mirrored_y']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<double> get fontSize =>
      columnsByName['font_size']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get sideMargin =>
      columnsByName['side_margin']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get fontFamily =>
      columnsByName['font_family']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get alignment =>
      columnsByName['alignment']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get displayReadingIndicatorBoxes =>
      columnsByName['display_reading_indicator_boxes']!
          as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<double> get readingIndicatorBoxesHeight =>
      columnsByName['reading_indicator_boxes_height']!
          as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<bool> get displayVerticalMarginBoxes =>
      columnsByName['display_vertical_margin_boxes']!
          as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<double> get verticalMarginBoxesHeight =>
      columnsByName['vertical_margin_boxes_height']!
          as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<bool> get verticalMarginBoxesFadeEnabled =>
      columnsByName['vertical_margin_boxes_fade_enabled']!
          as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<double> get verticalMarginBoxesFadeLength =>
      columnsByName['vertical_margin_boxes_fade_length']!
          as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get countdownDuration =>
      columnsByName['countdown_duration']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get themeMode =>
      columnsByName['theme_mode']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get appPrimaryColor =>
      columnsByName['app_primary_color']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get prompterBackgroundColor =>
      columnsByName['prompter_background_color']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get prompterTextColor =>
      columnsByName['prompter_text_color']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<bool> get markdownEnabled =>
      columnsByName['markdown_enabled']! as i1.GeneratedColumn<bool>;
}

i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<double> _column_5(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'scroll_speed',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<bool> _column_6(String aliasedName) =>
    i1.GeneratedColumn<bool>(
      'mirrored_x',
      aliasedName,
      false,
      type: i1.DriftSqlType.bool,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'CHECK ("mirrored_x" IN (0, 1))',
      ),
    );
i1.GeneratedColumn<bool> _column_7(String aliasedName) =>
    i1.GeneratedColumn<bool>(
      'mirrored_y',
      aliasedName,
      false,
      type: i1.DriftSqlType.bool,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'CHECK ("mirrored_y" IN (0, 1))',
      ),
    );
i1.GeneratedColumn<double> _column_8(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'font_size',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<double> _column_9(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'side_margin',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<String> _column_10(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'font_family',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_11(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'alignment',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<bool> _column_12(String aliasedName) =>
    i1.GeneratedColumn<bool>(
      'display_reading_indicator_boxes',
      aliasedName,
      false,
      type: i1.DriftSqlType.bool,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'CHECK ("display_reading_indicator_boxes" IN (0, 1))',
      ),
    );
i1.GeneratedColumn<double> _column_13(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'reading_indicator_boxes_height',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<bool> _column_14(String aliasedName) =>
    i1.GeneratedColumn<bool>(
      'display_vertical_margin_boxes',
      aliasedName,
      false,
      type: i1.DriftSqlType.bool,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'CHECK ("display_vertical_margin_boxes" IN (0, 1))',
      ),
    );
i1.GeneratedColumn<double> _column_15(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'vertical_margin_boxes_height',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<bool> _column_16(String aliasedName) =>
    i1.GeneratedColumn<bool>(
      'vertical_margin_boxes_fade_enabled',
      aliasedName,
      false,
      type: i1.DriftSqlType.bool,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'CHECK ("vertical_margin_boxes_fade_enabled" IN (0, 1))',
      ),
    );
i1.GeneratedColumn<double> _column_17(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'vertical_margin_boxes_fade_length',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<double> _column_18(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'countdown_duration',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'theme_mode',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<int> _column_20(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'app_primary_color',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<int> _column_21(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'prompter_background_color',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<int> _column_22(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'prompter_text_color',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<bool> _column_23(String aliasedName) =>
    i1.GeneratedColumn<bool>(
      'markdown_enabled',
      aliasedName,
      false,
      type: i1.DriftSqlType.bool,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'CHECK ("markdown_enabled" IN (0, 1))',
      ),
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from1To2: from1To2),
);
