name: Build

on:
  push:
    branches:
      - "release/**"

jobs:
  build-linux:
    name: Debug Build

    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: app
          submodules: recursive
          fetch-depth: 0

      - name: Compile
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends \
            clang cmake git \
            ninja-build pkg-config \
            libgtk-3-dev liblzma-dev \
            libstdc++-12-dev
          mkdir package/
          ./tools/build.sh -t linux -f foss -b package/ -V
        working-directory: app
